name: "Alamofire CI"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  macOS:
    name: ${{ matrix.name }}
    runs-on: warpdev-${{ matrix.runsOn }}-arm64-3x
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_15.2"
            runsOn: macos-13
            name: "macOS 13, Xcode 15.2, Swift 5.9.2"
            testPlan: "macOS"
            outputFilter: xcbeautify --renderer github-actions
          - xcode: "Xcode_15.1"
            runsOn: macos-14
            name: "macOS 14, Xcode 15.1, Swift 5.9.1"
            testPlan: "macOS"
            outputFilter: xcbeautify --renderer github-actions
          - xcode: "Xcode_15.0.1"
            runsOn: macos-14
            name: "macOS 14, Xcode 15.0.1, Swift 5.9.0"
            testPlan: "macOS"
            outputFilter: xcbeautify --renderer github-actions
          - xcode: "Xcode_14.3.1"
            runsOn: macos-13
            name: "macOS 13, Xcode 14.3.1, Swift 5.8.0"
            testPlan: "macOS"
            outputFilter: xcbeautify --renderer github-actions
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.name }}
        run: |-
          set -o pipefail
          brew install alamofire/alamofire/firewalk || brew upgrade alamofire/alamofire/firewalk
          firewalk &
          env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire macOS" -destination "platform=macOS" -testPlan "${{ matrix.testPlan }}" clean test | ${{ matrix.outputFilter }}
  Catalyst:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_15.2"
            name: "Catalyst 15.2"
            runsOn: macos-13
          - xcode: "Xcode_15.1"
            name: "Catalyst 15.1"
            runsOn: macos-14
          - xcode: "Xcode_15.0.1"
            name: "Catalyst 15.0"
            runsOn: macos-14
          - xcode: "Xcode_14.3.1"
            name: "Catalyst 14.3.1"
            runsOn: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Firewalk
        run: brew install alamofire/alamofire/firewalk || brew upgrade alamofire/alamofire/firewalk && firewalk &
      - name: Catalyst
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire iOS" -destination "platform=macOS" clean test 2>&1 | xcbeautify --renderer github-actions
  iOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=17.2,name=iPhone 15 Pro"
            name: "iOS 17.2"
            testPlan: "iOS"
            xcode: "Xcode_15.2"
            runsOn: macos-13
          - destination: "OS=17.0,name=iPhone 15 Pro"
            name: "iOS 17.0"
            testPlan: "iOS"
            xcode: "Xcode_15.0.1"
            runsOn: macos-14
          - destination: "OS=16.4,name=iPhone 14 Pro"
            name: "iOS 16.4"
            testPlan: "iOS"
            xcode: "Xcode_14.3.1"
            runsOn: macos-13
          - destination: "OS=15.5,name=iPhone 13 Pro"
            name: "iOS 15.5"
            testPlan: "iOS-NoTS"
            xcode: "Xcode_14.3.1"
            runsOn: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Firewalk
        run: brew install alamofire/alamofire/firewalk || brew upgrade alamofire/alamofire/firewalk && firewalk &
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire iOS" -destination "${{ matrix.destination }}" -testPlan "${{ matrix.testPlan }}" clean test 2>&1 | xcbeautify --renderer github-actions
  tvOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=17.2,name=Apple TV"
            name: "tvOS 17.2"
            testPlan: "tvOS"
            xcode: "Xcode_15.2"
            runsOn: macos-13
          - destination: "OS=17.0,name=Apple TV"
            name: "tvOS 17.0"
            testPlan: "tvOS"
            xcode: "Xcode_15.0.1"
            runsOn: macos-14
          - destination: "OS=16.4,name=Apple TV"
            name: "tvOS 16.4"
            testPlan: "tvOS"
            xcode: "Xcode_14.3.1"
            runsOn: macos-13
          - destination: "OS=15.4,name=Apple TV"
            name: "tvOS 15.4"
            testPlan: "tvOS-NoTS"
            xcode: "Xcode_14.3.1"
            runsOn: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Firewalk
        run: brew install alamofire/alamofire/firewalk || brew upgrade alamofire/alamofire/firewalk && firewalk &
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire tvOS" -destination "${{ matrix.destination }}" -testPlan "${{ matrix.testPlan }}" clean test 2>&1 | xcbeautify --renderer github-actions
  visionOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/Xcode_15.2.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=1.0,name=Apple Vision Pro"
            name: "visionOS 1.0"
            testPlan: "visionOS"
            scheme: "Alamofire visionOS"
            runsOn: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Firewalk
        run: brew install alamofire/alamofire/firewalk || brew upgrade alamofire/alamofire/firewalk && firewalk &
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}" -testPlan "${{ matrix.testPlan }}" clean test 2>&1 | xcbeautify --renderer github-actions
  watchOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=10.2,name=Apple Watch Series 9 (45mm)"
            name: "watchOS 10.2"
            testPlan: "watchOS"
            xcode: "Xcode_15.2"
            runsOn: macos-13
          - destination: "OS=10.0,name=Apple Watch Series 9 (45mm)"
            name: "watchOS 10.0"
            testPlan: "watchOS"
            xcode: "Xcode_15.0.1"
            runsOn: macos-14
          - destination: "OS=9.4,name=Apple Watch Series 8 (45mm)"
            name: "watchOS 9.4"
            testPlan: "watchOS"
            xcode: "Xcode_14.3.1"
            runsOn: macos-13
          - destination: "OS=8.5,name=Apple Watch Series 7 (45mm)"
            name: "watchOS 8.5"
            testPlan: "watchOS-NoTS"
            xcode: "Xcode_14.3.1"
            runsOn: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Firewalk
        run: brew update && brew install alamofire/alamofire/firewalk || brew upgrade alamofire/alamofire/firewalk && firewalk &
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire watchOS" -destination "${{ matrix.destination }}" -testPlan "${{ matrix.testPlan }}" clean test 2>&1 | xcbeautify --renderer github-actions
  SPM:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_15.2"
            runsOn: macos-13
            name: "macOS 13, SPM 5.9.2 Test"
            outputFilter: xcbeautify --renderer github-actions
          - xcode: "Xcode_15.1"
            runsOn: macos-14
            name: "macOS 14, SPM 5.9.1 Test"
            outputFilter: xcbeautify --renderer github-actions
          - xcode: "Xcode_15.0.1"
            runsOn: macos-14
            name: "macOS 14, SPM 5.9.0 Test"
            outputFilter: xcbeautify --renderer github-actions
          - xcode: "Xcode_14.3.1"
            runsOn: macos-13
            name: "macOS 13, SPM 5.8.0 Test"
            outputFilter: xcbeautify --renderer github-actions
    steps:
      - uses: actions/checkout@v4
      - name: Install Firewalk
        run: brew install alamofire/alamofire/firewalk || brew upgrade alamofire/alamofire/firewalk xcbeautify && firewalk &
      - name: Test SPM
        run: swift test -c debug | ${{ matrix.outputFilter }}
  CodeQL:
    name: Analyze with CodeQL
    runs-on: macos-13
    env:
      DEVELOPER_DIR: "/Applications/Xcode_14.3.1.app/Contents/Developer"
    timeout-minutes: 10
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: swift
      - name: Build macOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "Alamofire macOS" -destination "platform=macOS" clean build | xcpretty
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:swift"
